##ansible-playbook  task1.yml -e file_state=touch
---
- hosts: all
  tasks:
  - name: create a file on a remote machine
    file:
      dest: /tmp/file
      state: '{{file_state}}'

- hosts: web
  tasks:
  - name: create file on web machines
    file:
      dest: /tmp/web-file
      state: '{{file_state}}'

- hosts: all:!db
  tasks:
  - name: create file on web machines
    file:
      dest: /tmp/web-not-db-file
      state: '{{file_state}}'

- hosts: all:&backup:!web
  tasks:
  - name: create file on web machines
    file:
      dest: /tmp/backup-file
      state: '{{file_state}}'
